//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Template_4333
{
    using System;
    using System.Collections.Generic;
    
    public partial class zad2_table
    {
        public int IDDB { get; set; }
        public string ID { get; set; }
        public string OrderCode { get; set; }
        public string DateOfCreation { get; set; }
        public string OrderTime { get; set; }
        public string ClientCode { get; set; }
        public string Services { get; set; }
        public string Status { get; set; }
        public string ClosingDate { get; set; }
        public string RentalTime { get; set; }
    }
}
